#!/usr/bin/env bash
# A Bash script that installs and configures Nginx on a server

sudo apt-get update
sudo apt-get -y install nginx

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

service nginx start
