#!/usr/bin/env bash
# A Bash script that installs and configures Nginx on a server
apt-get -y update
apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
