#!/usr/bin/env bash
# A Bash script that installs and configures Nginx on a server
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
