#!/usr/bin/env bash
# Configure a custom 404 page
sudo apt-get update -y
sudo apt-get install nginx -y

echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

sudo sed -i '25i\	error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
