#!/usr/bin/env bash
# Install and configure HAproxy on a server
# Distrubte traffic between web-01 and web-02 using roundrobin algorithm
sudo apt-get -y update
sudo apt-get -y install haproxy=2.8.\*

sudo echo -e "
frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 373025-web-01 100.25.136.168:80 check
    server 373025-web-02 100.26.9.198:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
