#!/usr/bin/env bash
# Install and configure HAproxy on a server
# Distrubte traffic between web-01 and web-02 using roundrobin algorithm
sudo apt-get -y update
sudo apt-get -y install haproxy

lb_config="\nfrontend my_frontend\n\tbind *:80\n\tdefault_backend servers\n\nbackend servers\n\tbalance roundrobin\n\tserver 373025-web-01 100.25.136.168:80 check\n\tserver 373025-web-02 100.26.9.198:80 check"

echo -e $lb_config | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart
