#!/usr/bin/env bash
# Display the content of the file /etc/passwd, using the while loop + IFS
while IFS=: read -r username pass uid gid gecos home cmd; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $cmd. $uid's place is protected by the passcode $pass, more info about the user here: $gecos"
done < /etc/passwd
